# Generated by Django 5.1.7 on 2025-09-16 12:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Base_App', '0005_itemlist_slug_alter_booktable_name_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='itemlist',
            name='slug',
            field=models.SlugField(max_length=60, unique=True),
        ),
    ]
