# Generated by Django 5.1.7 on 2025-09-22 08:12

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Base_App', '0007_cart_cartitem'),
    ]

    operations = [
        migrations.CreateModel(
            name='Offer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('description', models.TextField(blank=True)),
                ('discount_percent', models.DecimalField(decimal_places=2, max_digits=5, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)])),
                ('start_date', models.DateTimeField()),
                ('end_date', models.DateTimeField()),
                ('is_active', models.BooleanField(default=True)),
                ('image', models.ImageField(blank=True, null=True, upload_to='offers/')),
                ('categories', models.ManyToManyField(blank=True, related_name='offers', to='Base_App.itemlist')),
                ('items', models.ManyToManyField(blank=True, related_name='offers', to='Base_App.items')),
            ],
            options={
                'ordering': ['-start_date'],
            },
        ),
    ]
